version: '2'
services:
  # The Application
  app:
    build:
      context: ./docker
      dockerfile: app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
    environment:
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=1"
      - "DB_PORT=3306"
      - "DB_HOST=mariadb"
      - "host=localhost"

  # The Web Server
  web:
    build:
      context: ./docker
      dockerfile: web.docker
    working_dir: /var/www
    depends_on:
      - mariadb
    volumes_from:
      - app
    ports:
      - 8091:80

  composer:
    restart: 'no'
    image: composer
    command: install --no-dev --optimize-autoloader
    volumes_from:
      - app
    working_dir: /var/www

  # The Database
  mariadb:
    image: mariadb:10.2
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: chinook

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8000:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

volumes:
  db:
